services:

  mysql:
    image: mysql:8.0

    container_name: mysql

    restart: always

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 20

    environment:
      MYSQL_DATABASE: Mobile
      MYSQL_USER: ajay
      MYSQL_PASSWORD: password123
      MYSQL_ROOT_PASSWORD: rootpassword

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    networks:
      - backend

  api:
    build: .

    container_name: erd-api

    depends_on:
      mysql:
        condition: service_healthy

    ports:
      - "8001:8000"

    env_file:
      - .env
    networks:
      - backend

volumes:
  mysql_data:

networks:
  backend:
    driver: bridge